language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: YM5jIus0td3HioKxvquJ1jtrbIpgJ74Wz/OLHyahUUbRufMVAgaLCQLuYtk/WggtBHI1TY8XzoEji08rn3E2rGilFXLQ/rg4VXAcpzPF6BdaBvHsdZfXT/mWJhhcNpTu/x7tDmbPYyiR56XvJqpRVYAONXIrqu1X4Q9s0/K78NviANcvCySbEoaYbziJ9+ATuZvYFLNIL2WFxLdoNjBk9U7xt5jSaflPq4QuBul4e0j538YdSrKew7G8lQ82gj9zlgVRmJoDJsRziOmICjw+C0tojh7UFeDlkYWIjLiJ0D/DCz78R8L5Whr833tUd0aD2ror1yxu04yF6Ii4nocVBmodA013AItU6llV8pgOSml54EhXUlSFScD3iqKAraKg4iPr7UhmUVoLq8qLWsKiSCC7JEhXnhPlLZTA7qhkdsyCeSCutZ5/w2a4h11se67BNxTPnF1lNWMCj/J/FCQFkHm4KEKLPMG7YSSnFy1kKkX5QYYfu1SN6uQ7bfmDMyBVvusI5kioN4iHSS1aLhX9WS1VLzFfV5oQeXSzOnGMueoh3ntBoJK9pYHOS3QZL3lbzBLFaCGNxPD+JsQP5X28lArTLUQcBA9JzXClUzojWKkdH83DM1BqClwbwMlkFG1euWQbETXY2k/BgaHBgF/ApwDV5IEiAr/GAwqCJEFxlvs=
