language: java
jdk:
- oraclejdk8
script:
- mvn test
deploy:
  api_key:
    secure: sHAcss+lHHzUU+eYkgjIQsHg1GocZdF7irNPag3/Qf6ZM00j+JA5azTWdyv5ZUPkO8XUAKHpvpnSPa/Za1FGDHVdrndZoxEjXKQwEgYhdyqRI6LM36WeJlcVGbnhxhsP/V9n3yEeEsgL1U0FCUiv2E3hoHjVmY5Db5qQhbtOF3fw0wYodMVQyvGiOILPOsncYr8KHAMyd1c3ZgSDo8gv6cPgUYA9P/RJJh5LOtk+auNQYtbxz+eLq7ltWzE/oK5fHGmLpyuQewk73LA70CetbENWOdmfyN8rJchhB34nTvBrsjXz1o/1gbILuV7OVtyH80jgfr9m+502F5lUsR5HPsGBK5DX/tjkMqJCsryPQmWd4pjUsa2P1prcIHiFRrBIKTtFPkNKgQ8fyQ49qCC8NN9heYmE9rDM4z0rBgpwV4w4tl8dp2mypRgElL+B/Eyrpxktil7WT1bxy7ZfR8GRMhjFxcR0ZvvMeCiUsTij5T5xcsHpVYvNdzSl+DhbG5GXty2S5QNrLr0BqUE4rTna+Od2u8b0yNPd7UyWvn7TJL9INu/mQUYPFSYnegrezYbDtpAgy07zgQK6pJvds+Vy4bYMKnUn1KwHp77T1GPOOn3Mz/arw1n7CvrtobtgSmSdqAnSeoNHiNTPEHiyiEL8Tf+gXERzMLcB4uc7DK9UVGw=
