INSERT INTO TB_SPECIE (CO_SEQ_SPECIE, NAME, DISTRIBUTION, MEDICAL_IMPORTANCE) VALUES (1, 'Lycosa' , 'Centro Oeste', false );
INSERT INTO TB_SPECIE (CO_SEQ_SPECIE, NAME, DISTRIBUTION, MEDICAL_IMPORTANCE) VALUES (2, 'Argiope' , 'Centro Oeste', false );
INSERT INTO TB_SPECIE (CO_SEQ_SPECIE, NAME, DISTRIBUTION, MEDICAL_IMPORTANCE) VALUES (3, 'Caranguejeira' , 'Centro Oeste', false );
INSERT INTO TB_SPECIE (CO_SEQ_SPECIE, NAME, DISTRIBUTION, MEDICAL_IMPORTANCE) VALUES (4, 'Cyrtophora' , 'Centro Oeste', false );

INSERT INTO TB_QUESTION (CO_SEQ_QUESTION, CONTENT) VALUES (1, 'Onde foi avistada?');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION) VALUES (1, 'Avistada no chão', 1);
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION) VALUES (2, 'Avistada em teia', 1);
INSERT INTO TB_QUESTION (CO_SEQ_QUESTION, CONTENT) VALUES (2, 'Como é a pelagem?');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION) VALUES (3, 'Grande e com muitos pelos', 2);
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION) VALUES (4, 'Pelagem peguena', 2);
INSERT INTO TB_QUESTION (CO_SEQ_QUESTION, CONTENT) VALUES (3, 'Qual o padrão da teia?');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION) VALUES (5, 'Teia vertical', 3);
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION) VALUES (6, 'Teia horizontal, com fios de suporte', 3);

INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (1, 1, 1);
INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (2, 1, 4);
INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (3, 3, 1);
INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (4, 3, 3);
INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (5, 2, 2);
INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (6, 2, 5);
INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (7, 4, 2);
INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (8, 4, 6);

