INSERT INTO TB_SPECIE (CO_SEQ_SPECIE, NAME, DISTRIBUTION, MEDICAL_IMPORTANCE) VALUES (1, 'Lycosa' , 'Centro Oeste', false );
INSERT INTO TB_SPECIE (CO_SEQ_SPECIE, NAME, DISTRIBUTION, MEDICAL_IMPORTANCE) VALUES (2, 'Argiope' , 'Centro Oeste', false );
INSERT INTO TB_SPECIE (CO_SEQ_SPECIE, NAME, DISTRIBUTION, MEDICAL_IMPORTANCE) VALUES (3, 'Caranguejeira' , 'Centro Oeste', false );
INSERT INTO TB_SPECIE (CO_SEQ_SPECIE, NAME, DISTRIBUTION, MEDICAL_IMPORTANCE) VALUES (4, 'Cyrtophora' , 'Centro Oeste', false );

INSERT INTO TB_QUESTION (CO_SEQ_QUESTION, CONTENT, FIRST ) VALUES (1, 'Em que ambiente foi avistada?', true);
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (1, 'Ambiente Urbano (quintal, parques, etc)', 1, 'images-options/chao.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (2, 'Ambiente Urbano (edificações, prédios)', 1, 'images-options/teia.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (3, 'Ambiente Natural (cerrado/mata/ambiente natural)', 1, 'images-options/teia.jpg');
INSERT INTO TB_QUESTION (CO_SEQ_QUESTION, CONTENT) VALUES (2, 'Onde foi avistada?');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (4, 'Andando pelo chão', 2, 'images-options/pelos_grandes.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (5, 'Em substrato vertical (plantas, paredes, etc)', 2, 'images-options/pelos_pequenos.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (6, 'Em teia aérea (orbicular)', 2, 'images-options/pelos_pequenos.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (7, 'Em teia difusa', 2, 'images-options/pelos_pequenos.jpg');
INSERT INTO TB_QUESTION (CO_SEQ_QUESTION, CONTENT) VALUES (3, 'A aranha possui pelagem?');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (8, 'Sim, abundante', 3, 'images-options/teia_vertical.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (9, 'Sim, poucos', 3, 'images-options/teia_horizontal.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (10, 'Ausente ou imperceptível', 3, 'images-options/teia_horizontal.jpg');
INSERT INTO TB_QUESTION (CO_SEQ_QUESTION, CONTENT) VALUES (4, 'Qual o tamanho do corpo (sem as patas)?');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (11, 'Grande (maior que 2 cm)', 3, 'images-options/teia_vertical.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (12, 'Mediano (1 - 2 cm)', 3, 'images-options/teia_horizontal.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (13, 'Pequeno (0,5 - 1 cm)', 3, 'images-options/teia_horizontal.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (14, 'Muito Pequeno (menor que 0,5 cm)', 3, 'images-options/teia_horizontal.jpg');
INSERT INTO TB_QUESTION (CO_SEQ_QUESTION, CONTENT) VALUES (5 , 'Como são as patas?');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (15, 'Grossas', 3, 'images-options/teia_vertical.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (16, 'Medianas', 3, 'images-options/teia_horizontal.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (17, 'Longas e finas', 3, 'images-options/teia_horizontal.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (18, 'Medianas e longas', 3, 'images-options/teia_horizontal.jpg');
INSERT INTO TB_QUESTION (CO_SEQ_QUESTION, CONTENT) VALUES (6 , 'Qual o posicionamento das patas?');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (19, 'Voltadas para frente ou para trás', 3, 'images-options/teia_vertical.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (20, 'Voltadas para os lados', 3, 'images-options/teia_horizontal.jpg');
INSERT INTO TB_QUESTION (CO_SEQ_QUESTION, CONTENT) VALUES (7 , 'Qual o posicionamento dos olhos?');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (21, 'Na borda anterior da carapaça', 3, 'images-options/teia_vertical.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (22, 'Na borda anterior e porção mediana da carapaça', 3, 'images-options/teia_horizontal.jpg');
INSERT INTO TB_QUESTION (CO_SEQ_QUESTION, CONTENT) VALUES (8 , 'Qual a coloração?');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (23, 'Colorida (mais de uma cor)', 3, 'images-options/teia_vertical.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (24, 'Escura: preta, cinza, marrom ou outros tons', 3, 'images-options/teia_horizontal.jpg');
INSERT INTO TB_CHARACTERISTIC_QUESTION (CO_SEQ_OPTION, DESCRIPTION, CO_QUESTION, IMAGE_ADDRESS) VALUES (25, 'Clara (bege, cinza, etc.)', 3, 'images-options/teia_horizontal.jpg');


INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (1, 1, 1);
INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (2, 1, 4);
INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (3, 3, 1);
INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (4, 3, 3);
INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (5, 2, 2);
INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (6, 2, 5);
INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (7, 4, 2);
INSERT INTO RL_SPECIE_CHARACTERISTIC (CO_SEQ_SPECIE_CHARACTERISTIC, CO_SPECIE, CO_OPTION) VALUES (8, 4, 6);

INSERT INTO TB_NEXT_QUESTION (CO_ID_NEXT_QUESTION, CO_CURRENT_QUESTION, CO_RESPONSE, CO_NEXT_QUESTION) VALUES (1, 1, 1, 2);
INSERT INTO TB_NEXT_QUESTION (CO_ID_NEXT_QUESTION, CO_CURRENT_QUESTION, CO_RESPONSE, CO_NEXT_QUESTION) VALUES (2, 1, 2, 3);

INSERT INTO TB_IMAGE_SPECIE (CO_SEQ_SPECIE, ADDRESS) VALUES (1, 'images-spiders/lycosa.jpg');
INSERT INTO TB_IMAGE_SPECIE (CO_SEQ_SPECIE, ADDRESS) VALUES (2, 'images-spiders/argiope.jpg');
INSERT INTO TB_IMAGE_SPECIE (CO_SEQ_SPECIE, ADDRESS) VALUES (3, 'images-spiders/caranguejeira.jpg');
INSERT INTO TB_IMAGE_SPECIE (CO_SEQ_SPECIE, ADDRESS) VALUES (4, 'images-spiders/cyrtophora.jpg');

